default: &default
  adapter: postgresql
  pool: 30
  timeout: 5000
  variables:
    statement_timeout: 10000

development: &development
  <<: *default
  database: nats_demo_development

test:
  <<: *development
  database: nats_demo_test

production:
  <<: *default
  database: nats_demo_production
